---
name: docslab tests
on:
    push:
    pull_request:
jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node: ['18', '20', '22.4']
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
                cache: yarn
            - uses: actions/setup-python@v5
              if: ${{ matrix.node == 18 }}
              with:
                  python-version: '3.10'
                  cache: 'pip'
            - name: Installation
              run: yarn install --frozen-lockfile
            - name: Integration installations
              if: ${{ matrix.node == 18 }}
              run: |
                pushd integrations/sphinx
                pip install .[test]
                popd
                pushd integrations/mkdocs
                pip install .[test]
                popd
            - name: Lint
              if: ${{ matrix.node == 18 }}
              run: |
                yarn format:check
                yarn lint
            - name: Test
              run: yarn test
            - name: Run end-to-end tests
              uses: cypress-io/github-action@v6
              with:
                start: yarn start
                wait-on: 'http://localhost:8080'

    docs:
        needs: [build-and-test]
        name: Documentation examples
        runs-on: ubuntu-22.04
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '18'
                cache: yarn
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
                  cache: 'pip'
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Build Docusaurus example
              run: |
                cd examples/docusaurus
                yarn install
                yarn build
                cd ../..
            - name: Build Sphinx example
              run: |
                cd examples/sphinx
                pip install sphinx
                pip install sphinx-docslab
                sphinx-build . build
                cd ../..
            - name: Build MkDocs example
              run: |
                cd examples/mkdocs
                pip install mkdocs
                pip install mkdocs-docslab
                mkdocs build
                cd ../..
            - name: Build mdBook example
              run: |
                cd examples/mdbook
                cargo install --path .
                mdbook build
                cd ../..
            - name: Build simple HTML examples
              run: |
                yarn install
                yarn run webpack build --env fullBundle --env example
                mv lib examples-html
            - name: Gather the examples
              run: |
                mkdir -p docs/examples
                mv examples/docusaurus/build docs/examples/docusaurus
                mv examples/sphinx/build docs/examples/sphinx
                mv examples/mkdocs/site docs/examples/mkdocs
                mv example/mdbook/book docs/examples/mdbook
                mv examples-html docs/examples/html
                cp doc/index.html docs/
            - name: Push to GitHub Pages branch
              run: |
                PAGES_BRANCH="github_pages"
                git config --global user.name 'GitHub Actions'
                git config --global user.email '<>'
                mv docs new-docs
                git fetch origin $PAGES_BRANCH
                git checkout -b $PAGES_BRANCH
                echo -n 'docslab.org' > new-docs/CNAME
                rm -rf docs
                mv new-docs docs
                touch docs/.nojekyll
                git add -f docs
                git commit -m 'GitHub Pages: built documentation'
                git push -f origin $PAGES_BRANCH
